fix crash with build type "release" (fix #16)
The app could crash suddenly when exiv2 or libexif encounter an exception.
This is because the java exception classes thrown in C/C++ code got deleted
by minifying. Thus throwing this exception:

  java.lang.ClassNotFoundException: com.exifthumbnailadder.app.Exiv2ErrorException

Fix is to add "@Keep" anotation in these java classes.