Tests: wait until the dir exists in DocumentsUI before click
Because of falkyness with this error (eg API31):

UiObjectNotFoundException: UiSelector[TEXT=test_standard_addThumbsSettingsFixMissingOff, RESOURCE_ID=android:id/title]