Tests: try to fix test flakyness when moving to AddThumbsFragment
Error was (on API29):

androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 179, 1720 and precision: 16, 16' on view 'view.getId() is <2131361793/com.exifthumbnailadder.app.debug:id/AddThumbsFragment>'.